SET IDENTITY_INSERT [dbo].[ElectricalEquipments] ON
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (2, N'вентилятор', 0.05, 0.6)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (3, N'компьютер', 0.4, 0.7)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (4, N'компьютер', 0.48, 0.7)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (5, N'кондиционер', 0.9, 0.6)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (6, N'кондиционер', 1.5, 0.6)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (7, N'кондиционер', 2, 0.6)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (8, N'кофеварка', 2, 0.1)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (9, N'ксерокс', 0.6, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (10, N'ксерокс ', 0.1, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (11, N'кулер', 0.42, 0.1)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (12, N'кулер', 0.5, 0.1)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (13, N'магнитола', 0.011, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (14, N'микроволновая печь', 1, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (15, N'музыкальный центр', 0.2, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (16, N'МФУ', 0.2, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (17, N'МФУ', 0, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (18, N'МФУ', 0.6, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (19, N'МФУ', 0.9, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (20, N'ноутбук', 0.1, 0.7)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (21, N'Освещение', 0.01, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (22, N'Освещение', 0.02, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (23, N'Освещение', 0.04, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (24, N'Освещение', 0.06, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (25, N'освещение', 0.072, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (26, N'принтер', 0.05, 0.3)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (27, N'принтер', 0.25, 0.3)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (28, N'принтер', 0.55, 0.3)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (29, N'рекламная вывеска', 0.4, 0.5)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (30, N'светящая вывеска', 1, 0.4)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (31, N'телевизор', 0.3, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (32, N'факс', 0.05, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (33, N'факс', 0.07, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (34, N'факс', 0.15, 0.2)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (35, N'холодильник', 0.1, 0.5)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (36, N'электрочайник', 2, 0.1)
INSERT INTO [dbo].[ElectricalEquipments] ([Id], [Name], [Power], [Coefficient]) VALUES (37, N'электрочайник', 2.1, 0.1)
SET IDENTITY_INSERT [dbo].[ElectricalEquipments] OFF
